# -*- coding: utf-8 -*-
"""stud_pred.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hL-h-Op7ZjSu4ZzPpOP1yM1yIvBQKC7K
"""

# Student Marks Prediction Using Machine Learning

# Import Libraries
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score

# Load Dataset
df = pd.read_csv('student_scores.csv')

# Display Dataset
print("First 5 Rows of Dataset:\n")
print(df.head())

# Check Dataset Information
print("\nDataset Information:\n")
print(df.info())

# Define Features and Target
X = df[['Hours']]
y = df['Scores']

# Split Dataset into Training and Testing
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Create Linear Regression Model
model = LinearRegression()

# Train Model
model.fit(X_train, y_train)

# Predict Test Data
y_pred = model.predict(X_test)

# Compare Actual and Predicted Values
results = pd.DataFrame({
    'Actual Marks': y_test,
    'Predicted Marks': y_pred
})

print("\nPrediction Results:\n")
print(results)

# Model Evaluation
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("\nMean Absolute Error:", mae)
print("R2 Score:", r2)

# Predict Student Marks for New Study Hours
study_hours = pd.DataFrame({'Hours': [7]})

predicted_marks = model.predict(study_hours)

print("\nPredicted Marks for 7 Hours of Study:")
print(predicted_marks[0])

# Visualization
plt.figure(figsize=(8,5))

# Scatter Plot
plt.scatter(X, y)

# Regression Line
plt.plot(X, model.predict(X))

# Labels and Title
plt.xlabel("Study Hours")
plt.ylabel("Marks")
plt.title("Student Marks Prediction using Linear Regression")

# Show Graph
plt.show()